"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { formatRupiah, joeProducts, type TqProgram } from "./site-data";

export function CartClient() {
  const [items, setItems] = useState([
    { ...joeProducts[1], qty: 1 },
    { ...joeProducts[2], qty: 1 },
  ]);
  const subtotal = useMemo(() => items.reduce((sum, item) => sum + item.price * item.qty, 0), [items]);
  const shipping = subtotal >= 100000 ? 0 : 10000;
  const total = subtotal + shipping;
  const changeQty = (name: string, delta: number) => setItems((prev) => prev.map((item) => item.name === name ? { ...item, qty: Math.max(1, item.qty + delta) } : item));
  const remove = (name: string) => setItems((prev) => prev.filter((item) => item.name !== name));

  return <div className="cart-layout container">
    <section className="cart-main">
      <div className="cart-title-row"><div><h1>🛒 KERANJANG BELANJA</h1><p>Review produk Anda sebelum melanjutkan ke pengiriman.</p></div><Link href="/joe-coffee">Lanjut Belanja →</Link></div>
      <div className="cart-table">
        <div className="cart-head"><span>Produk</span><span>Harga</span><span>Jumlah</span><span>Subtotal</span></div>
        {items.map((item) => <div className="cart-row" key={item.name}>
          <div className="cart-product"><img src={item.image} alt={item.name}/><div><strong>Joe Coffee {item.name}</strong><span>Blend Robusta & Arabika</span><span>Dari Temanggung & Wonosobo</span></div></div>
          <b>{formatRupiah(item.price)}</b>
          <div className="qty"><button onClick={() => changeQty(item.name, -1)}>−</button><span>{item.qty}</span><button onClick={() => changeQty(item.name, 1)}>+</button></div>
          <div className="subtotal-cell"><b>{formatRupiah(item.price * item.qty)}</b><button aria-label="Hapus" onClick={() => remove(item.name)}>⌫</button></div>
        </div>)}
      </div>
      <div className="promo-row"><div><strong>Punya Kode Promo?</strong><div className="promo-input"><input placeholder="Masukkan kode promo"/><button>Gunakan</button></div></div><div className="shipping-note"><span>🚚</span><div><strong>{shipping === 0 ? "Gratis Ongkir" : "Ongkir Hemat"}</strong><small>Belanja minimal Rp100.000</small></div><b>✓</b></div></div>

      <h2 className="recommend-title">Anda Mungkin Juga Suka</h2>
      <div className="recommend-grid">{joeProducts.filter((p) => !items.some(i => i.name === p.name)).slice(0,5).map((p) => <article key={p.name}><img src={p.image} alt={p.name}/><strong>{p.name}</strong><span>{p.subtitle}</span><b>{formatRupiah(p.price)}</b><button onClick={() => setItems((prev) => [...prev, {...p, qty:1}])}>＋ Keranjang</button></article>)}</div>
    </section>
    <aside className="order-summary"><h2>RINGKASAN PESANAN</h2><div><span>Subtotal ({items.length} produk)</span><b>{formatRupiah(subtotal)}</b></div><div><span>Ongkos Kirim</span><b>{shipping ? formatRupiah(shipping) : "Gratis"}</b></div><div><span>Promo</span><b>- Rp 0</b></div><hr/><div className="total"><span>Total Pembayaran</span><b>{formatRupiah(total)}</b></div><button className="gold-btn wide">Lanjut ke Pengiriman →</button><small>🔒 Transaksi aman dan data Anda terjaga</small></aside>
  </div>;
}

export function RegistrationForm({ program }: { program: TqProgram }) {
  const [success, setSuccess] = useState(false);
  const [format, setFormat] = useState("Online");
  const [payment, setPayment] = useState("QRIS");
  return <>
    <section className="registration-hero">
      <div className="container registration-hero-grid"><div><span className="eyebrow">◌ PENDAFTARAN PROGRAM</span><h1>Mulai Perjalanan Belajar<br/>Anda Bersama TQ</h1><p>Lengkapi data pendaftaran di bawah ini untuk mengikuti program pilihan Anda.</p></div><div className="selected-program"><span>PROGRAM YANG DIPILIH</span><h2>{program.title}</h2><p>{program.tagline}</p><div className="selected-meta"><b>◷ {program.duration}</b><b>▣ {format}</b><b>▣ {program.openTraining}</b></div><h4>YANG ANDA DAPATKAN</h4><ul>{program.benefits.slice(0,6).map(x => <li key={x}>✓ {x}</li>)}</ul></div></div>
    </section>
    <form className="registration-form container" onSubmit={(e) => {e.preventDefault(); setSuccess(true); window.scrollTo({top:document.body.scrollHeight, behavior:"smooth"});}}>
      <section className="form-card participant-card"><h2>DATA PESERTA</h2><p>Informasi Pribadi</p><div className="form-grid two"><label>Nama Lengkap *<input required placeholder="Masukkan nama lengkap Anda"/></label><label>Email *<input required type="email" placeholder="nama@email.com"/></label><label>Nomor WhatsApp *<input required placeholder="08xxxxxxxxxx"/></label><label>Nama Perusahaan / Instansi<input placeholder="Masukkan nama perusahaan / instansi"/></label><label>Jabatan / Posisi<input placeholder="Masukkan jabatan / posisi Anda"/></label></div></section>
      <section className="form-card format-card"><h2>PILIH FORMAT PELATIHAN</h2><p>Pilih format yang paling sesuai dengan kebutuhan Anda.</p><div className="choice-grid">{["Online","Offline","Hybrid","In-House Training"].map(x => <button type="button" onClick={() => setFormat(x)} className={format===x?"choice active":"choice"} key={x}><span>{x==="Online"?"💻":x==="Offline"?"👥":x==="Hybrid"?"▣":"🏢"}</span><b>{x}</b><small>{x === "Online" ? "Mengikuti pelatihan secara virtual dari mana saja." : x === "Offline" ? "Mengikuti pelatihan langsung di lokasi yang telah ditentukan." : x === "Hybrid" ? "Pilihan mengikuti pelatihan secara online maupun offline." : "Program khusus untuk perusahaan atau organisasi Anda."}</small></button>)}</div></section>
      <section className="form-card schedule-card"><h2>PILIH JADWAL</h2><p>Pilih jadwal pelatihan yang tersedia.</p><div className="schedule-layout"><div className="calendar"><div className="calendar-head">‹ <b>Juni 2026</b> ›</div><div className="days"><span>Sen</span><span>Sel</span><span>Rab</span><span>Kam</span><span>Jum</span><span>Sab</span><span>Min</span>{Array.from({length:30},(_,i)=><b className={i+1===18?"selected-day":""} key={i}>{i+1}</b>)}</div></div><div className="schedule-detail"><h3>Detail Jadwal</h3><p>▣ <b>Kamis – Jumat,<br/>18 – 19 Juni 2026</b></p><p>◷ <b>09.00 – 16.00 WIB</b></p><p>⌖ <b>{format === "Online" ? "Online (Zoom Meeting)" : "Lokasi menyesuaikan format"}</b></p><p>♙ <b>18 dari 30 peserta tersedia</b></p></div></div></section>
      <section className="form-card summary-card"><h2>RINGKASAN PENDAFTARAN</h2><div><span>Program</span><b>{program.title}</b></div><div><span>Format</span><b>{format}</b></div><div><span>Tanggal</span><b>18 – 19 Juni 2026</b></div><div><span>Peserta</span><b>1 Orang</b></div><div><span>Investasi per peserta</span><b>{program.openTraining}</b></div><hr/><div className="summary-total"><span>TOTAL INVESTASI</span><b>{program.openTraining}</b></div></section>
      <section className="form-card confirm-card"><h2>KONFIRMASI PENDAFTARAN</h2><label className="check"><input required type="checkbox"/> Saya telah membaca dan menyetujui Syarat & Ketentuan TQ Business & Learning Center.</label><label className="check"><input required type="checkbox"/> Saya menyetujui penggunaan data saya untuk kebutuhan administrasi pendaftaran program.</label><button className="gold-btn" type="submit">KONFIRMASI & LANJUTKAN →</button></section>
      <section className="form-card payment-card"><h2>PEMBAYARAN</h2><p>Pilih metode pembayaran yang paling nyaman untuk Anda.</p><div className="payment-grid">{["QRIS","Virtual Account","Transfer Bank","E-Wallet"].map(x => <button type="button" onClick={() => setPayment(x)} className={payment===x?"payment active":"payment"} key={x}><span>{x === "QRIS" ? "▦" : x === "Virtual Account" ? "VA" : x === "Transfer Bank" ? "🏦" : "▣"}</span><b>{x}</b><small>{x === "QRIS" ? "Bayar dengan aplikasi pembayaran yang mendukung QRIS." : x === "Virtual Account" ? "Pembayaran melalui rekening virtual." : x === "Transfer Bank" ? "Transfer ke rekening resmi TQ." : "Pilihan pembayaran digital yang tersedia."}</small></button>)}</div></section>
      {success ? <section className="form-card success-card"><span>✓</span><div><h2>PENDAFTARAN BERHASIL!</h2><h3>Selamat! Pendaftaran Anda Berhasil.</h3><p>Terima kasih telah mendaftar di TQ Business & Learning Center. Tim kami akan menghubungi Anda untuk proses berikutnya.</p><div className="success-meta"><b>Program: {program.title}</b><b>Tanggal: 18 – 19 Juni 2026</b><b>Status: Pendaftaran diterima</b></div></div></section> : null}
    </form>
  </>;
}

export function ConsultationForm() {
  const [sent, setSent] = useState(false);
  const [format, setFormat] = useState("In-House Training");
  return <form className="consult-layout container" onSubmit={(e)=>{e.preventDefault();setSent(true);}}>
    <main className="consult-main form-card"><h1>KONSULTASI PROGRAM</h1><p>Ceritakan kebutuhan pengembangan kompetensi di perusahaan Anda. Tim TQ akan membantu memberikan rekomendasi program terbaik.</p>
      <h2>▧ INFORMASI PERUSAHAAN</h2><div className="form-grid two"><label>Nama Perusahaan / Instansi *<input required placeholder="Masukkan nama perusahaan / instansi"/></label><label>Industri / Bidang Usaha *<select required defaultValue=""><option value="" disabled>Pilih industri / bidang usaha</option><option>Manufaktur</option><option>Jasa</option><option>Retail</option><option>Teknologi</option><option>Pendidikan</option><option>Lainnya</option></select></label><label>Nama PIC *<input required placeholder="Masukkan nama lengkap PIC"/></label><label>Jabatan *<input required placeholder="Masukkan jabatan"/></label><label>Email *<input required type="email" placeholder="nama@email.com"/></label><label>Nomor WhatsApp *<input required placeholder="08xxxxxxxxxx"/></label></div>
      <h2>▧ KEBUTUHAN TRAINING</h2><div className="form-grid"><label>Tujuan Konsultasi *<select required defaultValue=""><option value="" disabled>Pilih tujuan utama</option><option>Meningkatkan kompetensi</option><option>Meningkatkan kinerja tim</option><option>Pengembangan leadership</option><option>Menyelesaikan masalah bisnis</option><option>Custom program</option></select></label><label>Area / Kompetensi yang Dibutuhkan *<select required defaultValue=""><option value="" disabled>Pilih area atau kompetensi</option><option>Leadership</option><option>HR & Talent</option><option>Teamwork</option><option>KPI & Performance</option><option>Sales</option><option>Service Excellence</option><option>AI & Productivity</option></select></label><label>Tantangan / Masalah yang Dihadapi *<textarea required rows={5} placeholder="Ceritakan tantangan atau masalah yang sedang dihadapi perusahaan Anda"/></label><div className="form-grid three"><label>Jumlah Peserta (Estimasi)<input placeholder="Contoh: 20 orang"/></label><label>Level Peserta *<select required defaultValue=""><option value="" disabled>Pilih level peserta</option><option>Staff</option><option>Supervisor</option><option>Manager</option><option>Direksi</option><option>Campuran</option></select></label><label>Target Waktu Pelaksanaan *<select required defaultValue=""><option value="" disabled>Pilih bulan / periode</option><option>1 bulan ke depan</option><option>1–3 bulan</option><option>3–6 bulan</option><option>Fleksibel</option></select></label></div></div>
      <h2>♡ PREFERENSI PROGRAM</h2><label>Format Program yang Diinginkan</label><div className="choice-grid four">{["Online","Offline","Hybrid","In-House Training"].map(x => <button type="button" className={format===x?"choice active":"choice"} onClick={()=>setFormat(x)} key={x}><span>{x === "Online" ? "💻" : x === "Offline" ? "👥" : x === "Hybrid" ? "▣" : "🏢"}</span><b>{x}</b></button>)}</div><div className="form-grid two"><label>Durasi Program yang Diinginkan<select defaultValue=""><option value="">Pilih durasi</option><option>1 hari</option><option>2 hari</option><option>3 hari</option><option>Custom</option></select></label><label>Anggaran (Estimasi)<select defaultValue=""><option value="">Pilih range anggaran</option><option>&lt; Rp15 juta</option><option>Rp15–25 juta</option><option>Rp25–50 juta</option><option>&gt; Rp50 juta</option></select></label></div><label>Catatan Tambahan<textarea rows={3} placeholder="Tuliskan kebutuhan khusus / catatan tambahan lainnya (jika ada)"/></label><label className="check"><input required type="checkbox"/> Saya menyetujui bahwa data yang saya berikan akan digunakan untuk keperluan konsultasi program.</label><div className="form-actions"><button type="reset" className="outline-btn">↻ Reset Form</button><button type="submit" className="gold-btn">Kirim Permintaan Konsultasi ↗</button></div>{sent ? <div className="consult-success"><b>✓ Terima kasih. Permintaan konsultasi Anda telah kami terima.</b><p>Tim TQ akan mempelajari kebutuhan Anda dan menghubungi PIC untuk diskusi lebih lanjut.</p></div> : null}
    </main>
    <aside className="consult-aside"><section className="dark-panel"><span>PROGRAM CUSTOM UNTUK ANDA</span><h2>Program disesuaikan dengan kebutuhan perusahaan.</h2><ul><li>✓ Tujuan dan kebutuhan perusahaan</li><li>✓ Level dan jumlah peserta</li><li>✓ Industri dan budaya organisasi</li><li>✓ Durasi dan metode pelatihan</li><li>✓ Materi dan studi kasus relevan</li><li>✓ Lokasi dan jadwal pelaksanaan</li><li>✓ Anggaran program</li></ul></section><section className="side-panel"><h3>CONTOH PROGRAM POPULER</h3>{["Leadership for Business Performance","High Performance Team","Strategic HR & Talent Management","Sales Excellence & Consultative Selling","Customer Experience & Service Excellence"].map(x=><div key={x}>◌ {x} <span>›</span></div>)}<Link href="/tq-business">Lihat 10 Program Unggulan TQ</Link></section><section className="blue-panel"><h3>SETELAH MENGIRIM FORM</h3><p><b>◉ Tim TQ akan menghubungi Anda</b><br/>Maksimal 1x24 jam setelah form diterima.</p><p><b>◉ Diskusi kebutuhan lebih lanjut</b><br/>Kami akan menggali kebutuhan Anda secara detail.</p><p><b>◉ Kami kirimkan rekomendasi program</b><br/>Anda akan menerima proposal & penawaran.</p><p><b>◉ Program siap dijalankan</b><br/>Kami dampingi sampai program selesai.</p></section></aside>
  </form>;
}
