import Link from "next/link";
import { JoeCoffeeBuyButton } from "../cart-rules";
import { Breadcrumb, BenefitStrip, PageShell, SectionTitle } from "../site-ui";
import { formatRupiah, joeProducts } from "../site-data";

export default function JoeCoffeePage(){
  return <PageShell active="Joe Coffee"><main><section className="coffee-hero"><Breadcrumb>Joe Coffee</Breadcrumb><div className="container coffee-hero-grid"><div><h1>JOE COFFEE</h1><h2>Joyfulness Starts From Here</h2><p>Kopi blend pilihan Robusta & Arabika dari Temanggung dan Wonosobo.<br/>Tidak terlalu pahit, tidak terlalu asam.<br/>Dibuat untuk menemani setiap momen Anda.</p><div className="hero-mini-features"><div>◉<span>Blend Robusta<br/>& Arabika</span></div><div>△<span>Asal Biji Pilihan<br/>Temanggung & Wonosobo</span></div><div>☕<span>Rasa Seimbang<br/>Tidak Terlalu Pahit</span></div><div>♧<span>Tanpa Campuran<br/>Pengawet</span></div></div></div><div className="coffee-hero-product"><div className="glow"/><img className="bag" src="/produk-kopi-bubuk-500gr.jpeg" alt="Joe Coffee Pouch"/><img className="logo" src="/joe-coffee-logo-brand.webp" alt="Joe Coffee"/></div></div></section>
    <section className="section-pad white"><div className="container"><SectionTitle title="PRODUK JOE COFFEE"/><div className="product-grid five">{joeProducts.map(p=><article className="product-card" key={p.name}><div className="product-image"><img src={p.image} alt={p.name}/></div><h3>{p.name}</h3><p>{p.subtitle}</p><strong>{formatRupiah(p.price)}</strong><JoeCoffeeBuyButton product={p}/></article>)}</div></div></section>
    <section className="serving-section"><div className="container"><SectionTitle title="KENIKMATAN DI SETIAP SAJIAN"/><div className="serving-grid"><div><img src="/produk-es-kopi.webp" alt="Kopi Tubruk"/><b>Kopi Tubruk</b><span>Klasik, kuat, dan penuh aroma.</span></div><div><img src="/produk-es-kopi-susu.webp" alt="Kopi Susu Gula Aren"/><b>Kopi Susu Gula Aren</b><span>Manis alami, lembut di lidah.</span></div><div><img src="/produk-joe-espresso.webp" alt="Espresso"/><b>Espresso & Coffee Based</b><span>Aneka kopi modern pilihan Anda.</span></div><div><img src="/produk-es-kopi-jahe-serai.webp" alt="Kopi Susu Jahe Serai"/><b>Kopi Susu Jahe Serai</b><span>Hangat, segar, menenangkan.</span></div><div className="origin-card"><h3>Biji Kopi Pilihan</h3><strong>Temanggung & Wonosobo</strong><p>Kami memilih biji kopi terbaik dari dataran tinggi untuk rasa yang konsisten, aromatik, dan berkualitas.</p><Link className="outline-btn light" href="/tentang-kami">Selengkapnya →</Link></div></div></div></section>
    <BenefitStrip items={[["🚚","Pengiriman Cepat & Aman","Kopi sampai dengan aman dan tepat waktu."],["▣","Kemasan Premium","Menjaga kesegaran kopi."],["◉","100% Biji Kopi Pilihan","Tanpa campuran dan tanpa pengawet."],["◌","Layanan Pelanggan","Siap membantu Anda kapan saja."]]}/>
  </main></PageShell>
}
